---
- hosts: websever
  tasks:

    - name: Log into DockerHub
      docker_login:
        registry: docker.io
        username: prasannakumar24
        password: prasanna@24
        
    - name: pull an image
      docker_image:
        name: "prasannakumar24/praticedeployimage:28"
        source: pull

    - name: remove container
      docker_container:
        name: devopsAppDeploy
        state: absent
        
    - name: create a application container
      docker_container:
        name: devopsAppDeploy
        image: "prasannakumar24/praticedeployimage:28"
        state: started
        ports:
          - "8111:8080"
